# This is a sample build configuration for Clojure.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: clojure:lein-2.7.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - lein cljsbuild once
          - lein compile
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD